name: Update Extention Store
on: 
  push:
    paths:
      - "extensions.json"
    branches:
      - main
  workflow_dispatch:
    branches:
    - main

jobs:
  regenerate:
    name: Update Extension Store
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - name: Install Packages
        run: yarn --cwd ./scripts
      - name: Run Cloudflare Deployment
        run: yarn --cwd ./scripts run deploy
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_WEBHOOK: ${{ secrets.EXTENSION_STORE_DEPLOY_WEBHOOK }}
      - name: Notify Discord ExtensionsAccouncements Channel
        run: yarn --cwd ./scripts run trigger
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
