name: Validate Matter
on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
    paths:
      - "extensions.json"
jobs:
  comment:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Install Packages
        run: yarn --cwd ./scripts install --frozen-lockfile
      - name: Run Manifest File Validation
        id: validation
        run: |
          echo "result<<EOF" >> $GITHUB_OUTPUT
          node --no-warnings ./scripts/validation/manifest.js >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.validation.outputs.result }}
            })
